name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Windows MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: latest
          vulkan-components: 'Vulkan-Headers, Vulkan-Loader'
          vulkan-use-cache: true

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          
      - name: Install Ninja & Ccache
        run: choco install ninja ccache -y
        
      - name: Setup Ccache Environment
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-
          variant: ccache

      - name: Configure CMake
        run: |
          cmake -B build -S . `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Funkin-Windows
          path: export/release/Funkin.exe
